# Adversarial Attack Config
defaults:
  - default
  - _self_

# checkpoint
checkpoint_path: '/nfs/kun2/users/yifei/llm_rl/gpt2_bc_detective.pt'
save_path: '/nfs/kun2/users/yifei/llm_rl/dqn_adventure_1'

# env
env_name: adventure
env_load_path: '/nfs/kun2/users/yifei/llm_rl/ArCHer/dataset/detective.z5'

# training hyperparameters
rollout_size: 128 #number of rollout trajectories for each update
batch_size: 8
iterations: 2000 #total number of iterations
epochs: 50 #number of epochs for the critic each iteration
actor_epochs: 3 #number of epochs for the actor each iteration
warmup_iter: 10 #number of iterations without updating the policy
grad_accum_steps: 32
critic_lr: 2e-5
lm_lr: 1e-5


# wandb logging
use_wandb: False
project_name: 'llm_rl_20q'
run_name: 'archer-acc'